"""
Telegram Alert System - Send signals to Telegram channel
Uses Telegram Bot API (no external dependencies)
"""
import aiohttp
import json
from typing import Dict, List, Optional
from datetime import datetime
from pathlib import Path


class TelegramAlerter:
    """
    Send trading signals and alerts to Telegram channel/group.
    
    Setup:
    1. Create bot via @BotFather on Telegram
    2. Get bot token
    3. Add bot to your channel/group as admin
    4. Get channel ID (forward a message to @userinfobot)
    """
    
    def __init__(self, bot_token: str, chat_id: str):
        self.bot_token = bot_token
        self.chat_id = chat_id
        self.base_url = f"https://api.telegram.org/bot{bot_token}"
        self.session: Optional[aiohttp.ClientSession] = None
    
    async def _get_session(self) -> aiohttp.ClientSession:
        if self.session is None or self.session.closed:
            self.session = aiohttp.ClientSession()
        return self.session
    
    async def close(self):
        if self.session and not self.session.closed:
            await self.session.close()
    
    async def send_message(self, text: str, parse_mode: str = 'HTML') -> bool:
        """Send a text message"""
        try:
            session = await self._get_session()
            data = {
                'chat_id': self.chat_id,
                'text': text,
                'parse_mode': parse_mode
            }
            
            async with session.post(f"{self.base_url}/sendMessage", json=data) as resp:
                result = await resp.json()
                if result.get('ok'):
                    print(f"✅ Telegram alert sent")
                    return True
                else:
                    print(f"❌ Telegram error: {result}")
                    return False
        except Exception as e:
            print(f"❌ Telegram send failed: {e}")
            return False
    
    async def send_signal(self, signal: Dict) -> bool:
        """Send a trade signal alert"""
        side_emoji = '🟢' if signal.get('side') == 'LONG' else '🔴' if signal.get('side') == 'SHORT' else '⚪'
        
        text = f"""
{side_emoji} <b>SWARM SIGNAL</b> {side_emoji}

<b>Symbol:</b> {signal.get('symbol', 'N/A')}
<b>Action:</b> {signal.get('side', 'N/A')}
<b>Entry:</b> ${signal.get('entry', 0):,.2f}

<b>🎯 Take Profit:</b> ${signal.get('take_profit', 0):,.2f}
<b>🛑 Stop Loss:</b> ${signal.get('stop_loss', 0):,.2f}

<b>📊 R:R Ratio:</b> {signal.get('rr_ratio', 0):.2f}:1
<b>💰 Position Size:</b> {signal.get('position_size', 0):.4f} units
<b>🎯 Confidence:</b> {signal.get('confidence', 0):.0%}

<b>⏰ Time:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

<i>🤖 Generated by Swarm Trader</i>
        """.strip()
        
        return await self.send_message(text)
    
    async def send_no_trade(self, symbol: str, reason: str):
        """Send no-trade alert"""
        text = f"""
⚪ <b>NO TRADE</b> ⚪

<b>Symbol:</b> {symbol}
<b>Reason:</b> {reason}

<i>🤖 Swarm Trader - Waiting for better setups</i>
        """.strip()
        
        return await self.send_message(text)
    
    async def send_market_update(self, prices: Dict[str, Dict]):
        """Send market price update"""
        text = "📊 <b>MARKET UPDATE</b>\n\n"
        
        for symbol, data in prices.items():
            price = data.get('price', 0)
            change = data.get('change_24h', 0)
            change_emoji = '📈' if change > 0 else '📉' if change < 0 else '➡️'
            
            text += f"{symbol}: ${price:,.2f} {change_emoji} ({change:+.2f}%)\n"
        
        text += f"\n<i>🕐 {datetime.now().strftime('%H:%M:%S UTC')}</i>"
        
        return await self.send_message(text)
    
    async def send_drawdown_alert(self, drawdown_pct: float, threshold: float):
        """Send drawdown warning"""
        text = f"""
⚠️ <b>DRAWDOWN ALERT</b> ⚠️

<b>Current Drawdown:</b> {drawdown_pct:.2f}%
<b>Threshold:</b> {threshold:.2f}%

<b>⚡ Action Required:</b> Review positions and risk exposure

<i>🤖 Swarm Trader Risk Management</i>
        """.strip()
        
        return await self.send_message(text)
    
    async def send_daily_summary(self, stats: Dict):
        """Send daily performance summary"""
        text = f"""
📈 <b>DAILY SWARM SUMMARY</b> 📈

<b>📅 Date:</b> {datetime.now().strftime('%Y-%m-%d')}

<b>📊 Signals Generated:</b> {stats.get('signals_count', 0)}
<b>✅ Trades Executed:</b> {stats.get('trades_executed', 0)}
<b>🎯 Win Rate:</b> {stats.get('win_rate', 0):.1f}%
<b>💰 P&L:</b> {stats.get('pnl', 0):+.2f}%

<b>🤖 Agent Performance:</b>
"""
        
        for agent, perf in stats.get('agent_stats', {}).items():
            text += f"  • {agent}: {perf.get('success_rate', 0):.1f}% success\n"
        
        text += "\n<i>🤖 Swarm Trader - Building wealth autonomously</i>"
        
        return await self.send_message(text)
    
    async def test_connection(self) -> bool:
        """Test Telegram connection"""
        text = "🟢 <b>Swarm Trader Connected</b>\n\nTelegram alerts are working!"
        return await self.send_message(text)


def get_telegram_alerter() -> Optional[TelegramAlerter]:
    """
    Get Telegram alerter from config.
    
    Create config file: state/telegram_config.json
    {
        "bot_token": "YOUR_BOT_TOKEN",
        "chat_id": "YOUR_CHAT_ID"
    }
    """
    config_file = Path(__file__).parent.parent / "state" / "telegram_config.json"
    
    if not config_file.exists():
        print("⚠️ Telegram config not found. Create state/telegram_config.json")
        return None
    
    try:
        with open(config_file) as f:
            config = json.load(f)
        
        return TelegramAlerter(
            bot_token=config.get('bot_token', ''),
            chat_id=config.get('chat_id', '')
        )
    except Exception as e:
        print(f"❌ Failed to load Telegram config: {e}")
        return None


if __name__ == "__main__":
    import asyncio
    
    async def test():
        # Test with mock config
        alerter = TelegramAlerter(bot_token="MOCK_TOKEN", chat_id="MOCK_CHAT")
        
        # Test signal
        signal = {
            'symbol': 'BTCUSD',
            'side': 'LONG',
            'entry': 95000,
            'stop_loss': 92000,
            'take_profit': 104000,
            'rr_ratio': 3.0,
            'position_size': 0.35,
            'confidence': 0.75
        }
        
        print("Testing signal format...")
        print(await alerter.send_signal(signal))
    
    asyncio.run(test())
